# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieListClean' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kingfisher'
  pod 'Cosmos'
  # Pods for MovieListClean

  target 'MovieListCleanTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieListCleanUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
